CREATE TABLE MEMBER
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    USERNAME   VARCHAR(20) NOT NULL,
    PASSWORD   VARCHAR(60) NOT NULL,
    EMAIL      VARCHAR(50),
    NAME       VARCHAR(30) NOT NULL,
    ROLE       VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    DELETED    BOOLEAN DEFAULT false,
    DELETED_AT TIMESTAMP
);

CREATE UNIQUE INDEX IDX_EMAIL ON MEMBER (EMAIL);
CREATE INDEX IDX_USERNAME ON MEMBER (USERNAME);
CREATE INDEX IDX_CREATED_AT ON MEMBER (CREATED_AT);

ALTER TABLE MEMBER
    ADD CONSTRAINT EMAIL_UNIQUE_CONSTRAINT UNIQUE(EMAIL);
